name: Tag and Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
    build:
        runs-on: macos-14
        steps:
        - uses: actions/checkout@v4
        - uses: dtolnay/rust-toolchain@stable

        - uses: taiki-e/cache-cargo-install-action@v2
          with:
            tool: cargo-edit

        - uses: taiki-e/cache-cargo-install-action@v2
          with:
            tool: cargo-get

        - run: cargo set-version --bump minor --locked
        
        - name: Commit files
          run: | 
            git config --local user.email "Roland.Szarka-Kovacs@meshx.co"
            git config --local user.name "szkabaroli"
            git commit -a -m "[skip ci] Bump versions"
            git tag $(cargo get package.version --pretty)
      
        - name: Push changes
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: ${{ github.ref }}
            tags: true